Dieta/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('alimentos.urls', namespace='alimentos')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alimentos/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', views.auth_login, name='authentication'),
    url(r'^logout$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^$', views.ListaAlimentos.as_view(), name='home'),
    url(r'^alimento/(?P<pk>[0-9]+)/$',
        views.DetalleAlimento.as_view(), name='detalle'),
    url(r'^alimento/nuevo', views.nuevo_alimento, name='nuevo')
]

alimentos/models.py
from __future__ import unicode_literals
from django.db import models
from tiposalimento.models import TipoAlimento


class Alimento(models.Model):
    nombre = models.CharField(max_length=255)
    porcion = models.CharField(max_length=255)
    descripcion = models.CharField(max_length=255)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ('id',)


class Alimento_Tipo(models.Model):
    alimento = models.ForeignKey(Alimento)
    tipo = models.ForeignKey(TipoAlimento)

    class Meta:
        verbose_name = 'TiposAlimentos'
        verbose_name_plural = 'TiposAlimentos'

    def __str__(self):
        return '%s %s' % (self.alimento.nombre, self.tipo.tipo)

tiposalimento/models.py
from __future__ import unicode_literals

from django.db import models


class TipoAlimento(models.Model):
    tipo = models.CharField(max_length=255)

    def __str__(self):
        return self.tipo

    class Meta:
        ordering = ('tipo',)

alimentos/forms.py
from django import forms
from .models import Alimento


class AlimentoForm(forms.ModelForm):
    class Meta:
        model = Alimento
        fields = '__all__'

alimentos/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

from django.views.generic import ListView
from django.views.generic.detail import DetailView

from .forms import AlimentoForm
from .models import Alimento


class ListaAlimentos(ListView):
    model = Alimento


class DetalleAlimento(DetailView):
    model = Alimento


@login_required()
def nuevo_alimento(request):
    if request.method == 'POST':
        form = AlimentoForm(request.POST, request.FILES)
        if form.is_valid():
            alimento = form.save()
            alimento.save()
            return HttpResponseRedirect('/')
    else:
        form = AlimentoForm()

    template = loader.get_template('nuevo_alimento.html')
    context = {
        'form': form
    }
    return HttpResponse(template.render(context, request))


def auth_login(request):
    if request.method == 'POST':
        action = request.POST.get('action', None)
        first_name = request.POST.get('first_name', None)
        last_name = request.POST.get('last_name', None)
        email = request.POST.get('email', None)
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        if action == 'signup':
            user = User.objects.create_user(first_name=first_name,
                                            last_name=last_name,
                                            username=username,
                                            password=password,
                                            email=email)
            user.save()
        elif action == 'login':
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
    context = {}
    return render(request, 'login/login.html', context)

tiposalimento/views.py
from django.shortcuts import render

# Create your views here.

templates/alimentos/alimento_detail.html
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
	<title>{{ alimento.nombre }}</title>
	<link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css" />
 	<link rel="stylesheet" href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>
<body>		
	<div class="panel-heading">
		<nav>
		  <ul class="pager">
		    <li class="previous"><a href="/"><span aria-hidden="true">&larr;</span> Atras</a></li>
		    <!-- <li class="next"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li> -->
		  </ul>
		</nav>		

		<div class="row" align="center">
		  <div class="col-sm-6 col-md-4">
		    <div class="thumbnail">
		      <img src="{{ alimento.image.url }}">
		      <div class="caption">
		        <h3>{{ alimento.nombre }}</h3>
		        <p>{{ alimento.porcion }}</p>	
		        <p>{{ alimento.descripcion }}</p>        
		      </div>
		    </div>
		  </div>
		</div>
	</div>
</body>
</html>

templates/alimentos/alimento_list.html
<!DOCTYPE <!DOCTYPE html>
<html lang="es-mx">
<head>
	{% load staticfiles %}
	<meta charset = "UTF-8">
	<title>Dieta</title>
	<link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css" />
 	<link rel="stylesheet" href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>
<body>	
	<div class="container">
		<div class="header clearfix">
	        <nav>
	          <ul class="nav nav-pills pull-right">
	            <li role="presentation" class="active"><a href="#">Alimentos</a></li>
	            <li role="presentation"><a href="#">Menu</a></li>
	            <li role="presentation"><a href="#">Contacto</a></li>
	          </ul>
	        </nav>
        	<h2 class="text-muted glyphicon glyphicon-scale"> Dieta</h2>
      	</div>  
      		<div align="right">      
        	 
			{% if user.is_authenticated %}
				<h3 class="text-muted">Hi {{ user.username }}</h3>
				<span class="glyphicon glyphicon-log-in">
					<a href="{% url "alimentos:logout" %}" class="btn btn-info" role="button">Logout</a>
				</span>
			{% else %}
				<span class="glyphicon glyphicon-log-out">
					<a href="{% url "alimentos:authentication" %}" class="btn btn-info" role="button">Login</a>
				</span>
			{% endif %}
			</div>
      	<ul class="nav nav-pills" role="tablist">
		  <li role="presentation"><a href="{% url "alimentos:nuevo" %}">Nuevo Alimento</a></li>
		  <!-- <li role="presentation"><a href="#">Profile</a></li>
		  <li role="presentation"><a href="#">Messages</a></li> -->
		</ul>

		<div class="panel panel-default">		
			<div class="panel-heading">
				<h2 class="panel-title" align="center">Menu de Alimentos</h2>
			</div>
				<div class="panel-body">
	  				<h4>Estos alimentos serán tus aliados para tu dieta:
		  				<span class="label label-success">1. Fruta</span>
		  				<span class="label label-success">2. Huevos</span>
		  				<span class="label label-success">3. Verduras</span></br></br>
		  				<span class="label label-success">4. Pollo o pavo</span>
		  				<span class="label label-success">5. Patatas</span>
		  				<span class="label label-success">6. Yogurt natural</span>
		  				<span class="label label-success">7. Pescados magros</span>
		  				<span class="label label-success">8. Tofu</span>
		  				<span class="label label-success">9. Ensaladas</span></br></br>
		  				<span class="label label-success">10. Espárragos</span>
		  				<span class="label label-info">Truco extra: el bendito agua</span>
		  			</h4>
		  		</div>
				<table class="table">
			  		<tr>
				  		<th>Alimento</th>
				  		<th>Porcion</th>
				  		<th>Tipo</th>
				  		<th>Descripcion</th>
				  		<th>Imagen</th>
			  		</tr>
					{% for a in object_list %}
					<tr>								
						<td><a href="{% url "alimentos:detalle" a.id %}"> {{ a.nombre }} </a></td>
						<td> {{ a.porcion }} </td>
						<td> {{ a.tipo }} </td> 
						<td> {{ a.descripcion|truncatewords:"10" }} </td>
						{% if a.image|length > 0 %}
							<td align="center"> <span class="glyphicon glyphicon-ok
" aria-hidden="true"></span> </td>
						{% else %}
							<td align="center"> <span class="glyphicon glyphicon-remove
" aria-hidden="true"></span> </td>
						{% endif %}
					</tr>
					{% endfor %}
			  </table>
			</div>
		</div>
	</div>
</body>
</html>

templates/login/login.html
<!DOCTYPE html>
<html lang="es-mx">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-login">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-6">
                                <a href="#" class="active" id="login-form-link">Login</a>
                            </div>
                            <div class="col-xs-6">
                                <a href="#" id="register-form-link">Registrar</a>
                            </div>
                        </div>
                        <hr>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <form id="login-form" action="" method="post" role="form" style="display: block;">
                                    {% csrf_token %}
                                    <input type="hidden" name="action" value="login">
                                    <div class="form-group">
                                        <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
                                    </div>
                                    <!-- <div class="form-group text-center">
                                        <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                                        <label for="remember"> Remember Me</label>
                                    </div> -->
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-6 col-sm-offset-3">
                                                <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- <div class="form-group">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="text-center">
                                                    <a href="http://phpoll.com/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div> -->
                                </form>
                                <form id="register-form" action="" method="post" role="form" style="display: none;">
                                    {% csrf_token %}    
                                    <input type="hidden" name="action" value="signup">
                                    <div class="form-group">
                                        <input type="text" name="first_name" id="first_name" tabindex="1" class="form-control" placeholder="Nombre" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" name="last_name" id="last_name" tabindex="2" class="form-control" placeholder="Apellido" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="email" name="email" id="email" tabindex="3" class="form-control" placeholder="Correo Electronico" value="">
                                    </div>                                    
                                    <div class="form-group">
                                        <input type="text" name="username" id="username" tabindex="4" class="form-control" placeholder="Usuario" value="">
                                    </div>                                    
                                    <div class="form-group">
                                        <input type="password" name="password" id="password" tabindex="5" class="form-control" placeholder="Contraseña">
                                    </div>
                                    <!-- <div class="form-group">
                                        <input type="password" name="confirm-password" id="confirm-password" tabindex="6" class="form-control" placeholder="Confirma Contraseña">
                                    </div> -->
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-6 col-sm-offset-3">
                                                <input type="submit" name="register-submit" id="register-submit" tabindex="6" class="form-control btn btn-register" value="Registrar">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/nuevo_alimento.html
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
	<title>Nuevo Alimento</title>
	<link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css" />
 	<link rel="stylesheet" href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" />
</head>
<body>
	<div class="container">
		<nav>
		  <ul class="pager">
		    <li class="previous"><a href="/"><span aria-hidden="true">&larr;</span> Atras</a></li>
		    <!-- <li class="next"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li> -->
		  </ul>
		</nav>
		<div class="panel panel-primary"> 
			<div class="panel-heading">
				<h3 class="panel-title">Nuevo Alimento</h3> 
			</div> 
			<div class="panel-body"> 
				<form method="POST" enctype="multipart/form-data">				
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-primary" type="submit">Guardar</button>
			</form>
			</div>
		</div>
	</div>
</body>
</html>